export default {
	login: "locspoc",
	id: 63437440,
	node_id: "MDQ6VXNlcjYzNDM3NDQw",
	avatar_url: "https://avatars.githubusercontent.com/u/63437440?v=4",
	gravatar_id: "",
	url: "https://api.github.com/users/locspoc",
	html_url: "https://github.com/locspoc",
	followers_url: "https://api.github.com/users/locspoc/followers",
	following_url:
		"https://api.github.com/users/locspoc/following{/other_user}",
	gists_url: "https://api.github.com/users/locspoc/gists{/gist_id}",
	starred_url: "https://api.github.com/users/locspoc/starred{/owner}{/repo}",
	subscriptions_url: "https://api.github.com/users/locspoc/subscriptions",
	organizations_url: "https://api.github.com/users/locspoc/orgs",
	repos_url: "https://api.github.com/users/locspoc/repos",
	events_url: "https://api.github.com/users/locspoc/events{/privacy}",
	received_events_url: "https://api.github.com/users/locspoc/received_events",
	type: "User",
	site_admin: false,
	name: "Loc Tran",
	company: null,
	blog: "https://www.linkedin.com/in/mrlocspoc/",
	location: "Adelaide, South Australia",
	email: null,
	hireable: true,
	bio: `Hello, my name is Loc Tran and I am a full stack web development, data analytics and digital marketing professional.

  Learn more... 
  https://loctran.com.au/`,
	twitter_username: "locspoc",
	public_repos: 22,
	public_gists: 1,
	followers: 0,
	following: 10,
	created_at: "2020-04-10T03:22:49Z",
	updated_at: "2022-11-04T12:19:52Z",
};
